### ISSUE TITLE
merge-maven-repos file upload order is not deterministic

### ISSUE THREAD

**Issue by jpraet** [mojohaus/wagon-maven-plugin#10]
We are using the org.codehaus.mojo:wagon-maven-plugin:1.0:merge-maven-repos to upload our artifacts to several nexus repositories (snapshots/staging/stable) in a continuous delivery pipeline.

Some of our artifacts have a custom maven packaging type (yaml), and sometimes nexus does not recognize these artifacts correctly.

We found out that it works in the cases where merge-maven-repos first uploads the pom.xml, and then the yaml file. In the cases where it first uploads the yaml file, and then the pom.xml it doesn't work.

I couldn't find any specification of the maven repository protocol, so I don't know if it is expected to upload the pom.xml first, and then the artifacts. It might be a bug in nexus.

**Comment by dantran** [comment]
some what relate to https://issues.apache.org/jira/browse/MDEPLOY-204 but not direct

your issue may be nexus specifics.

the plugin still have missing piece where you need to tell your remote maven repo to refresh/sync its metadata after upload completed
