### ISSUE TITLE
displayCommandOutputs doesn't print the output interactively

### ISSUE THREAD

**Issue by lrozenblyum** [mojohaus/wagon-maven-plugin#27]
I'm running a code snippet

```
<groupId>org.codehaus.mojo</groupId>
	<artifactId>wagon-maven-plugin</artifactId>
	<version>2.0.0</version>
	<executions>
	<execution>
			
	<id>...</id>
	<goals>
		<goal>sshexec</goal>
	</goals>
	<configuration>
	  <commands>
	      <command>... long_running.sh</command>
	  </commands>
          <displayCommandOutputs>true</displayCommandOutputs>
	</configuration>
</execution>
</executions>
```

The long_running.sh is a huge script that can run very long time.

EXPECTED:

I expected that (like Ant sshexec) the displayCommandOutputs will write the console output immediately when a line is printed by the .sh script

ACTUALLY:
The console output is printed only after org.codehaus.mojo:wagon-maven-plugin:sshexec finishes

**Comment by abccbaandy** [comment]
same issue

**Comment by zozidalom** [comment]
same for me
