### ISSUE TITLE
When the password contains @ will report error

### ISSUE THREAD

**Issue by lzc3905** [mojohaus/wagon-maven-plugin#28]
···
[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:sshexec (default-cli) on project Demo: Unable to create a Wagon instance for scp://root:p@ss@127.0.0.1/opt/demo: Cannot connect. Reason: java.net.UnknownHostException: ss@127.0.0.1 -> [Help 1]
···

**Comment by bmarwell** [comment]
URL password parameter needs to be URL encoded.
