### ISSUE TITLE
upload-single skip option removed 1.0 -> 2.0.0

### ISSUE THREAD

**Issue by jessefarinacci** [mojohaus/wagon-maven-plugin#29]
Please bring back this option. It is valuable for specifying common configuration in higher level poms and then unskipping in a wide number of child poms. DRY. Please bring back the option, it is nice. :) Thanks.

**Comment by afel** [comment]
Same for "upload" goal

**Comment by dantran** [comment]
fixed at 4b4f1d3167cdf232400f157c58fa64315d2a1c8d

**Comment by jpraet** [comment]
Any ETA on release 2.0.1?

**Comment by jpraet** [comment]
The fix was reverted again just before the 2.0.1 release? 4d67a10db987ca8a7fa2ca7e021ae7f49f9e5c62

**Comment by dantran** [comment]
It was accidentally reverted due to javadoc annotation no longer support and failed 2.0.1 release build
will put it back in 2.0.2 soon

**Comment by dantran** [comment]
@jpraet please help to verify again 2.0.2 currently at staging repo https://oss.sonatype.org/content/groups/staging/

**Comment by jpraet** [comment]
@dantran yes, it works with the 2.0.2

**Comment by cdprete** [comment]
Hi.
I think the property is evaluated too early.

I've a (in version 2.0.2) a configuration like
```xml
<plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>wagon-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>deploy-rpm</id>
                                <phase>deploy</phase>
                                <goals>
                                    <goal>upload-single</goal>
                                </goals>
                                <configuration>
                                    <skip>${rpm.build.skip}</skip>
                                    <fromFile>${rpm.file-path}</fromFile>
                                    <serverId>${rpm.repository.id}</serverId>
                                    <url>${rpm.repository.url}/${rpm.file-name}/${rpm.file-version}</url>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```
where `rpm.build.skip` is dynamically set in a Groovy script. I've other plugins reading the exact same property in other phases and they're all skipped correctly but the `wagon-maven-plugin`.
