### ISSUE TITLE
Doesn't  support knownHostsProvider

### ISSUE THREAD

**Issue by shenliuyang** [mojohaus/wagon-maven-plugin#3]
Build in jenkins will cause dead loop.

**Comment by shenliuyang** [comment]
Are you sure you want to continue connecting? (yes/no): The authenticity of host '123.57.144.13' can't be established.
RSA key fingerprint is 04:d0:0b:04:5a:6c:e1:05:45:6a:b9:8c:47:aa:7d:54.
Are you sure you want to continue connecting? (yes/no): The authenticity of host '123.57.144.13' can't be established.
RSA key fingerprint is 04:d0:0b:04:5a:6c:e1:05:45:6a:b9:8c:47:aa:7d:54.
Are you sure you want to continue connecting? (yes/no): The authenticity of host '123.57.144.13' can't be established.
RSA key fingerprint is 04:d0:0b:04:5a:6c:e1:05:45:6a:b9:8c:47:aa:7d:54.
Are you sure you want to continue connecting? (yes/no): The authenticity of host '123.57.144.13' can't be established.
RSA key fingerprint is 04:d0:0b:04:5a:6c:e1:05:45:6a:b9:8c:47:aa:7d:54.

**Comment by dantran** [comment]
it is a known issue at jenkins where it feeds a linefeed into the prompt and cause the log to spill until you run out of diskspace.  It is not wagon-maven-plugin but at maven-site-pluging using wagon-ssh provider

**Comment by tmadan** [comment]
Hi guys 
i am also facing the issues , tried changing settings.xml , with following info , but i did not get any results , facing same issue .  if anyone know the solution , let me know
<server>
  <id>some-repo-id</id>
  <configuration>
    <knownHostsProvider implementation="org.apache.maven.wagon.providers.ssh.knownhost.NullKnownHostProvider">
      <hostKeyChecking>no</hostKeyChecking>
    </knownHostsProvider>
  </configuration>
</server>

**Comment by tmadan** [comment]
Hi guys 
i am also facing the issues , tried changing settings.xml , with following info , but i did not get any results , facing same issue .  if anyone know the solution , let me know

**Comment by vliska** [comment]
Same here. Even went through code and I don't see where it should set the knownHostsProvider to wagon-ssh. Settings.xml doesn't work, configuration in mojo doesn't work, configuration in pluginManagement doesn't work.

**Comment by dantran** [comment]
work around at  https://issues.apache.org/jira/browse/WAGON-467

**Comment by dantran** [comment]
wagon-467 does not solve this issue.  I know understand the issue a bit better.  it seems maven 3 is now place the responsibility to usingthe settings/server/configure to the plugin itself. this way the plugin does not have to lock to a maven version.

**Comment by dantran** [comment]
superseded by #6

**Comment by shenliuyang** [comment]
Embrace gradle you will enjoy yourself

**Comment by dantran** [comment]
fixed at #6 plus WAGON-467
