### ISSUE TITLE
Suppress logs when uploading to s3 

### ISSUE THREAD

**Issue by j3ffrw** [mojohaus/wagon-maven-plugin#31]
Given the ff
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>wagon-maven-plugin</artifactId>
            <version>1.0</version>
            <executions>
              <execution>
                <id>deploy-release</id>
                <phase>post-integration-test</phase>
                <goals>
                  <goal>upload</goal>
                </goals>
                <configuration>
                  <serverId>aws-release</serverId>
                  <url>s3://mybucket/report/</url>
                  <fromDir>${project.build.directory}/report/view</fromDir>
                  <toDir>${project.version}</toDir>
                </configuration>
              </execution>
            </executions>
          </plugin>

How do suppress the logging of s3 upload for each file?, my use case is that my project generate lots of report and logging them one by one, spams the log.
Sample logs to supress:
[INFO] Uploading /myproject/target/report/view/images/built-by-maven.png to s3://myproject/report//0.0.1-SNAPSHOT/images/built-by-maven.png ...
[INFO] Uploading: s3://myproject/report/view/0.0.1-SNAPSHOT/images/built-by-maven.png

**Comment by bmarwell** [comment]
@j3ffrw if you are still interested, I could implement a 'quiet' parameter for the upcoming 3.0.0 release. Or you could just create a PR yourself!

**Comment by j3ffrw** [comment]
hi @bmarwell , thank you for looking into this, having a "quiet" parameter is nice to have and I'll be willing to wait for the 3.0.0 release.
