### ISSUE TITLE
Directory variable interpolation of ${project.build.testResources} doesn't work properly

### ISSUE THREAD

**Issue by gerib** [mojohaus/wagon-maven-plugin#35]
<s>See https://stackoverflow.com/questions/53042572/directory-variable-interpolation-of-project-build-testresources-doesnt-work</s> ... which got deleted due to SE's [deletion model](https://stackoverflow.com/help/roomba) recently so here it is to the full now:

> I have a `wagon-maven-plugin` under Maven 3.5.4 in my `<build>/<plugins>` section with:
> 
>         <fromDir>${project.build.testResources}</fromDir>
>         <includes>file</includes>
> 
> This interpolates to:
> 
>     [INFO] --- wagon-maven-plugin:2.0.0:upload (publish-to-integration-test) @ <project> ---
>     ...
>     [DEBUG]   (f) fromDir = <project path>\[
>       Resource {targetPath: null, filtering: false,
>         FileSet {directory: <project path>\src\test\resources,
>           PatternSet [includes: {}, excludes: {}]}}]
>     [DEBUG]   (f) includes = file
>     ...
> 
> Note the empty `includes: {}`!
> 
> The result is:
> 
>     [INFO] Nothing to upload.
> 
> It works if I change `<fromDir>` to the explicit path string.
> 
> If I use `<fromDir>${project.build.directory}</fromDir>` in another POM it is reasonably not interpolated to a `Resource` object but to a simple path string:
> 
>     [DEBUG]   (f) fromDir = <project path>\target
> 
> and hence works there, too.
> 
> Is this a bug or a feature of `${project.build.testResources}`? But, if it is a feature, what the f...heck is it for?
> 
> ### UPDATE ###
> 
> I created [an according issue on GitHub][1].

[1]: https://github.com/mojohaus/wagon-maven-plugin/issues/35

**Comment by dantran** [comment]
looks to me Maven not interpolate ${project.build.testResources} at your pom, use  ${project.build.directory}/xxxx instead
