### ISSUE TITLE
Add .sha256/.sha512 to WagonDirectoryScanner.NOT_DIRECTORIES

### ISSUE THREAD

**Issue by snjeza** [mojohaus/wagon-maven-plugin#41]
Original issue - https://github.com/eclipse/eclipse.jdt.ls/issues/1486
I'm trying to download *wrapper.jar.sha256 files from https://services.gradle.org/distributions using the following pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>org.sample</artifactId>
	<groupId>sample</groupId>
	<version>1.0</version>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>wagon-maven-plugin</artifactId>
				<version>2.0.0</version>
				<executions>
					<execution>
						<id>gradle-checksums-release</id>
						<phase>validate</phase>
						<goals>
							<goal>download</goal>
						</goals>
						<configuration>
							<url>https://services.gradle.org/distributions</url>
							<includes>*wrapper.jar.sha256</includes>
							<toDir>${basedir}/gradle/checksums</toDir>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

https://services.gradle.org/distributions contains 900+ *.sha256 files. The wagon-download-plugin tests if those files are directories - https://github.com/mojohaus/wagon-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/wagon/shared/WagonDirectoryScanner.java#L365
Because of that, the build takes about 10 minutes on my machine. 
When I add .sha256 to WagonDirectoryScanner.NOT_DIRECTORIES, the build takes less than 10 seconds.

**Comment by bmarwell** [comment]
fixed in https://github.com/mojohaus/wagon-maven-plugin/pull/44
