### ISSUE TITLE
Query symbol in <fromFile>

### ISSUE THREAD

**Issue by aydinugur** [mojohaus/wagon-maven-plugin#43]
Hi all,

I am trying to run download-single goal with 1.0 version of wagon-maven-plugin but it gives me this error:

Error handling resource: Resource missing at http://myurl/from/file%3FWSDL 404 Not Found -> [Help 1]

My plugin definition is here

<plugin>

    <groupId>org.codehaus.mojo</groupId>
    <artifactId>wagon-maven-plugin</artifactId>
    <version>1.0</version>
    <executions>
        <execution>
            <id>fetch-wsdl</id>
            <phase>initialize</phase>
            <goals>
                <goal>download-single</goal>
            </goals>
            <configuration>
                <url>http://myurl</url>
                <fromFile>from/file?WSDL</fromFile>
                <toFile>${project.basedir}/src/main/resources/wsdl/Consumer.wsdl</toFile>
            </configuration>
        </execution>
    </executions>

If I use another url without query symbol in <fromFile> it works.

**Comment by dantran** [comment]
it is a known issue where URL with ?query would not work with this plugin

**Comment by aydinugur** [comment]
Thanks for the response, then I will look for bypassing query symbol or alternating the plugin ):

**Comment by dantran** [comment]
a replacement is antrun with 'get' task
