### ISSUE TITLE
is it possible to publish my packages to github?

### ISSUE THREAD

**Issue by RumoEL** [mojohaus/wagon-maven-plugin#48]
is it possible to publish my packages to github?
i use gpg-> ssh
receive / push code changes i can (git pull / push)
but can this be used to publish packages to github?

**Comment by RumoEL** [comment]
my [proj](https://github.com/rumoEL/rumo-parent)
what needs to be added to pom.xml to publish package with `mvn deploy`

**Comment by dantran** [comment]
from the surface, the answer is no. you may be able to obtain more advice posting at maven user list
