### ISSUE TITLE
Goals "download-single" and "download" are hanging on Maven 3.6.3 and Maven 3.8.4

### ISSUE THREAD

**Issue by AntoanetaAngelovaMarinova** [mojohaus/wagon-maven-plugin#51]
Our team is testing **wagon-maven-plugin** with different versions of Maven as we are planning to migrate from **Java 8** to **Java 11**. We want to upgrade Maven and Tycho version also. Are new versions of Maven compatible with the plugin?

**Goals "download-single" and "download" are hanging on Maven 3.6.3 and Maven 3.8.4.** We use **wagon-maven-plugin version 2.0.2**. We tested with different versions without any success. The file download starts but was not able to be completed. The upload is working as expected. The download is just hanging and we have only broken partially downloaded file. **It is working with Maven 3.5.4.**

**Example pom.xml file:**

```
<project>
	[...]
	<build>
		[...]
		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh</artifactId>
				<version>3.5.1</version>
			</extension>
		</extensions>

		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>wagon-maven-plugin</artifactId>
				<version>2.0.2</version>
				<executions>
					<execution>
						<id>upload-javadoc</id>
						<phase>compile</phase>
						<goals>
							<goal>upload</goal>
						</goals>
						<configuration>
							<fromDir>local.dir</fromDir>
							<includes>*</includes>
							<excludes>pom.xml</excludes>
							<url>scp://your.remote.host/</url>
							<toDir>remote.dir</toDir>
							<optimize>true</optimize>
							<serverId>remote.server.id</serverId>
						</configuration>
					</execution>
					<execution>
						<id>download-test-data</id>
						<phase>compile</phase>
						<goals>
							<goal>download</goal>
						</goals>
						<configuration>
							<serverId>remote.server.id</serverId>
							<url>scp://your.remote.host/</url>
							<fromDir>remote.dir</fromDir>
							<includes>**/*</includes>
							<toDir>local.dir</toDir>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	[...]
</project>
```
Update: tested also with wagon-ssh version 3.5.1. The download is still hanging.

**Comment by khmarbaise** [comment]
Is there a good reason why you are using an old wagon version 3.0.0 instead of most recent https://search.maven.org/artifact/org.apache.maven.wagon/wagon-ssh
