### ISSUE TITLE
Wagon-FTP Deprecation

### ISSUE THREAD

**Issue by mcwayliffe** [mojohaus/wagon-maven-plugin#52]
I noticed this morning that Maven's Wagon FTP provider [has been deprecated](https://github.com/apache/maven-wagon/commit/5106193db8eb18862d0df3142c31012248b8f1ef) to be removed in version`4.0.0`. Is there any plan for the `wagon-maven-plugin` to continue supporting FTP transfers once that happens?

**Comment by dantran** [comment]
IMO, this plugin should continue to work with maven4 using FTP provider since it is still using maven-wagon API 3.x
