### ISSUE TITLE
maven.plugin.validation warnings

### ISSUE THREAD

**Issue by msymons** [mojohaus/wagon-maven-plugin#55]
Building a project using Maven 3.9.x will generate plugin validation [WARNING] log entries.  These a intended to help spot problems that plugins might run into when Maven 4.x is released.

When using 'maven.plugin.validation' property with value "verbose", we see:

```
Plugin validation issues were detected in x plugin(s)

* org.codehaus.mojo:wagon-maven-plugin:2.0.2
 Declared at location(s):
  * XXX
 Used in module(s):
  * YYY
 Plugin issue(s):
  * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
  * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.2.5, org.apache.maven:maven-model:3.2.5, org.apache.maven:maven-core:3.2.5, org.apache.maven:maven-settings:3.2.5, org.apache.maven:maven-model-builder:3.2.5, org.apache.maven:maven-compat:3.2.5, org.apache.maven:maven-aether-provider:3.2.5, org.apache.maven:maven-repository-metadata:3.2.5, org.apache.maven:maven-settings-builder:3.2.5, org.apache.maven:maven-artifact:3.2.5]
 ```

The advise from Maven devs is:

> Do not rely on maven-compat, as if you do, it means your plugin is Maven2 plugin technically (you depend on Maven3's Maven2 compatibility layer)

**Comment by bmarwell** [comment]
fixed in: https://github.com/mojohaus/wagon-maven-plugin/issues/67
