### ISSUE TITLE
Settings.xml server httpConfiguration ignored

### ISSUE THREAD

**Issue by dantran** [mojohaus/wagon-maven-plugin#8]
https://issues.apache.org/jira/browse/WAGON-468

**Comment by dantran** [comment]
dup of #6

**Comment by jakub-bochenski** [comment]
FTR this now fails with `[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.1-SNAPSHOT:list (default-cli) on project standalone-pom: Unable to create a Wagon instance for https://jenkins.acme-internal.com/plugin/repository/project/acme-Installer-DSL/Build/1828/repository: While configuring wagon for 'jenkins': Unable to apply wagon configuration. Component does not implement interface org.codehaus.plexus.component.MapOrientedComponent -> [Help 1] `

**Comment by dantran** [comment]
it got it working by loading wagon-http-2.11-SNAPSHOT as maven extension.  See WagonMojoHttpSettingsTest

**Comment by jakub-bochenski** [comment]
@adamzovits I wouldn't hold my breath.

My suggestion is either:
 - build this version locally and release to your internal repository 
 - use a timestamped snapshot

**Comment by adamzovits** [comment]
@jakub-bochenski Thanks, I gave it a try but even after building everything and setting up the wagon-http-2.11-SNAPSHOT extension I got "Component does not implement interface org.codehaus.plexus.component.MapOrientedComponent", so this does not look like a promising avenue.

**Comment by dantran** [comment]
@tchemit i dont have any update on this

**Comment by jakub-bochenski** [comment]
Nice, how this was ignored for 7 years then closed
