### ISSUE TITLE
merge-maven-repos goal is parsing tar file contents thinking it's a HTML page

### ISSUE THREAD

**Issue by jakub-bochenski** [mojohaus/wagon-maven-plugin#9]
It starts like this:
```
[DEBUG] scandir: dir: com/acme/ui/29.4.0-SNAPSHOT/ vpath: com/acme/ui/29.4.0-SNAPSHOT/
https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ - Status code: 200
[DEBUG] scandir: dir: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.rpm vpath: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.rpm/
https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.rpm/ - Status code: 200
[DEBUG] scandir: dir: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar vpath: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/
https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/ - Status code: 200
[DEBUG] scandir: dir: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/javascript:void(0) vpath: com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/javascript:void(0)/
https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/javascript:void(0)/ - Status code: 200
```
After that it keeps adding more `javascript:void(0)/` segments in an infinite loop, going as far as `https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/javascript:void(0)/`

When I break the connection it fails with
```
org.apache.maven.wagon.TransferFailedException: I/O error reading HTML listing of artifacts: Premature end of Content-Length delimited message body (expected: 163225600; received: 65113743
        at org.apache.maven.wagon.providers.http.wagon.shared.HtmlFileListParser.parseFileList(HtmlFileListParser.java:106)
        at org.apache.maven.wagon.providers.http.HttpWagon.getFileList(HttpWagon.java:98)
        at org.apache.maven.wagon.providers.http.HttpWagon.getFileList(HttpWagon.java:46)
```
It seems that the plugin is downloading and trying to parse the file as if it was a HTML page, even though the file is clearly identified as `application/x-tar`
```
< Date: Wed, 07 Dec 2016 16:17:42 GMT
< X-Content-Type-Options: nosniff
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< ETag: ""
< Last-Modified: Wed, 07 Dec 2016 11:50:08 UTC
< Content-Type: application/x-tar
< Content-Length: 163225600
< Server: Jetty(9.2.z-SNAPSHOT)
< Strict-Transport-Security: max-age=31536000; includeSubDomains
```
This `tar` file actually include some HTML pages containing `javascript:void(0)` links.

The remote repository actually responds to requests for paths under `https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/javascript:void(0)` returning the tar file.

Also the URI is obviously interpreted wrongly -- it should read `javascript:` as scheme and act accordingly instead of treating it as a relative URL.

The remote repository is powered by https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Maven+Repository+Server

**Comment by jakub-bochenski** [comment]
After adding a HAProxy rule returning 404 to requests ending in `/javascript:void(0)` the plugin is failing with ```
[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.1-SNAPSHOT:merge-maven-repos (default-cli) on project standalone-pom: Error during performing repository copy: Illegal character in path at index 176: https://jenkins.acme-internal.com:3000/plugin/repository/project/acme-Installer-DSL/Build/1904/repository/com/acme/ui/29.4.0-SNAPSHOT/ui-29.4.0-20161207.115106-1904.tar/' + realUrl + '/ -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.1-SNAPSHOT:merge-maven-repos (default-cli) on project standalone-pom: Error during performing repository copy
```

It's because of a javascript file with a line containing `return '<a href="' + realUrl + '">'`

**Comment by dantran** [comment]
related to #7

wagon html support is very dumb as well

**Comment by tchemit** [comment]
H @jakub-bochenski , after several months...

Do you still got the problem ? I can try to help but I would need a project to test the defect. Thanks

**Comment by jakub-bochenski** [comment]
@tchemit I gave up on the wagon plugin completely in favour of the [deployer pom hack](https://gist.github.com/jakub-bochenski/7802ee7f44b8e3b99bdd69b2ab150e6c)

**Comment by tchemit** [comment]
Ok, thanks for your reply. Is it cool what you are using ?--Enjoy and ShareTony Chemit
          
            
            On avr. 12 2018, at 3:32 pm, jakub-bochenski <notifications@github.com> wrote:
            
            
              @tchemit I gave up on the wagon plugin completely in favour of the deployer pom hack

**Comment by jakub-bochenski** [comment]
Well it gets the job done. 

This required a change from a pull (running maven on the receiving end) to a push.
First I deploy the build results to a local repository with the help of `-DaltDeploymentRepository=file::default::file://$WORKSPACE/.m2repo`. Then I run the deployer pom on `$WORKSPACE/.m2repo`
